enum CONSTANTS {
  // 畫面
  OPEN_CLOSE_NAVBAR = "OPEN_CLOSE_NAVBAR",
  CHANGE_WORK_SPACE = "CHANGE_WORK_SPACE",
  // 卡片動作
  CREATE_CARD_LIST = "CREATE_CARD_LIST",
  ADD_CARD = "ADD_CARD",
  // 登入
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  // 會員
  GET_USER = "GET_USER",
  // 組織
  GET_ORGANIZATION = "GET_ORGANIZATION",
  UPDATE_ONE_ORGANIZATION = "UPDATE_ONE_ORGANIZATION",
}

export default CONSTANTS;
